// =====================================================
// GÉNÉRATEUR VCARD POUR ADD TO CONTACTS
// =====================================================

import { ContactData, VCardOptions } from '@/lib/types/contact-analytics'

/**
 * Génère une vCard au format 3.0 ou 4.0
 */
export class VCardGenerator {
  private data: ContactData
  private options: VCardOptions

  constructor(data: ContactData, options: VCardOptions = { version: '3.0', encoding: 'UTF-8', format: 'standard' }) {
    this.data = data
    this.options = options
  }

  /**
   * Génère la vCard complète
   */
  generate(): string {
    const lines: string[] = []
    
    // En-tête vCard
    lines.push('BEGIN:VCARD')
    lines.push(`VERSION:${this.options.version}`)
    lines.push(`PRODID:-//Ofika//Contact Generator//EN`)
    
    // Nom complet
    if (this.data.fullName) {
      lines.push(`FN:${this.escapeVCardValue(this.data.fullName)}`)
    }
    
    // Nom structuré (prénom, nom de famille)
    if (this.data.firstName || this.data.lastName) {
      const structuredName = [
        this.data.firstName || '',
        this.data.lastName || '',
        '', // middle name
        '', // prefix
        ''  // suffix
      ].join(';')
      lines.push(`N:${structuredName}`)
    }
    
    // Organisation
    if (this.data.company) {
      lines.push(`ORG:${this.escapeVCardValue(this.data.company)}`)
    }
    
    // Titre du poste
    if (this.data.jobTitle) {
      lines.push(`TITLE:${this.escapeVCardValue(this.data.jobTitle)}`)
    }
    
    // Email
    if (this.data.email) {
      lines.push(`EMAIL:${this.data.email}`)
    }
    
    // Téléphone
    if (this.data.phone) {
      lines.push(`TEL:${this.data.phone}`)
    }
    
    // Site web
    if (this.data.website) {
      const url = this.data.website.startsWith('http') ? this.data.website : `https://${this.data.website}`
      lines.push(`URL:${url}`)
    }
    
    // Adresse
    if (this.data.address || this.data.city || this.data.country) {
      const address = [
        '', // post office box
        '', // extended address
        this.data.address || '', // street address
        this.data.city || '', // locality
        '', // region
        '', // postal code
        this.data.country || '' // country
      ].join(';')
      lines.push(`ADR:${address}`)
    }
    
    // Réseaux sociaux
    if (this.data.linkedin) {
      const linkedinUrl = this.data.linkedin.startsWith('http') ? this.data.linkedin : `https://${this.data.linkedin}`
      lines.push(`URL;TYPE=linkedin:${linkedinUrl}`)
    }
    
    if (this.data.instagram) {
      const instagramHandle = this.data.instagram.startsWith('@') ? this.data.instagram : `@${this.data.instagram}`
      lines.push(`X-SOCIALPROFILE;TYPE=instagram:${instagramHandle}`)
    }
    
    // Photo (si disponible)
    if (this.data.photo) {
      lines.push(`PHOTO:${this.data.photo}`)
    }
    
    // Note/Bio
    if (this.data.bio) {
      lines.push(`NOTE:${this.escapeVCardValue(this.data.bio)}`)
    }
    
    // Métadonnées Ofika
    lines.push(`X-OFIKA-PROFILE:Generated by Ofika`)
    lines.push(`REV:${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z`)
    
    // Fin vCard
    lines.push('END:VCARD')
    
    return lines.join('\r\n')
  }

  /**
   * Génère un nom de fichier pour la vCard
   */
  generateFileName(): string {
    const name = this.data.fullName || 'contact'
    const sanitizedName = name
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 50)
    
    return `${sanitizedName}.vcf`
  }

  /**
   * Génère un Blob pour le téléchargement
   */
  generateBlob(): Blob {
    const vcardContent = this.generate()
    return new Blob([vcardContent], { 
      type: 'text/vcard;charset=utf-8' 
    })
  }

  /**
   * Génère une URL de téléchargement
   */
  generateDownloadUrl(): string {
    const blob = this.generateBlob()
    return URL.createObjectURL(blob)
  }

  /**
   * Échappe les caractères spéciaux pour vCard
   */
  private escapeVCardValue(value: string): string {
    return value
      .replace(/\\/g, '\\\\')
      .replace(/,/g, '\\,')
      .replace(/;/g, '\\;')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
  }
}

/**
 * Fonction utilitaire pour créer une vCard rapidement
 */
export function createVCard(data: ContactData, options?: Partial<VCardOptions>): string {
  const generator = new VCardGenerator(data, {
    version: '3.0',
    encoding: 'UTF-8',
    format: 'standard',
    ...options
  })
  
  return generator.generate()
}

/**
 * Fonction utilitaire pour télécharger une vCard
 */
export function downloadVCard(data: ContactData, options?: Partial<VCardOptions>): void {
  const generator = new VCardGenerator(data, {
    version: '3.0',
    encoding: 'UTF-8',
    format: 'standard',
    ...options
  })
  
  const blob = generator.generateBlob()
  const url = URL.createObjectURL(blob)
  const fileName = generator.generateFileName()
  
  // Créer un lien de téléchargement temporaire
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  link.style.display = 'none'
  
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  
  // Nettoyer l'URL
  URL.revokeObjectURL(url)
}

/**
 * Fonction utilitaire pour partager une vCard via Web Share API
 */
export async function shareVCard(data: ContactData, options?: Partial<VCardOptions>): Promise<boolean> {
  if (!navigator.share) {
    return false
  }
  
  try {
    const generator = new VCardGenerator(data, {
      version: '3.0',
      encoding: 'UTF-8',
      format: 'standard',
      ...options
    })
    
    const blob = generator.generateBlob()
    const fileName = generator.generateFileName()
    
    const file = new File([blob], fileName, { 
      type: 'text/vcard' 
    })
    
    await navigator.share({
      title: `Contact: ${data.fullName}`,
      text: `Ajouter ${data.fullName} à vos contacts`,
      files: [file]
    })
    
    return true
  } catch (error) {
    console.error('Error sharing vCard:', error)
    return false
  }
}

/**
 * Vérifie si l'API Web Share est supportée
 */
export function isWebShareSupported(): boolean {
  return typeof navigator !== 'undefined' && 'share' in navigator
}

/**
 * Vérifie si l'API Web Share supporte les fichiers
 */
export function isWebShareFilesSupported(): boolean {
  return typeof navigator !== 'undefined' && 
         'share' in navigator && 
         'canShare' in navigator &&
         navigator.canShare({ files: [new File([''], 'test.txt')] })
}